### ISSUE TITLE
Module 2: Update English Content

### ISSUE THREAD

**Issue by grvhi** [qgis/QGIS-Documentation#173]
## Task

We need to port the text of Module Two to QGIS 2.0.
#### Link To Current

http://manual.linfiniti.com/en/introduction/index.html
## Subtasks
- [x] Lesson 1: Text and Screenshots
      Assigned: George
- [x] Lesson 2: Text and Screenshots
      Assigned: George
- [x] Lesson 3: Text and Screenshots
      Assigned: George
