### ISSUE TITLE
Module 4: Update English Content

### ISSUE THREAD

**Issue by grvhi** [qgis/QGIS-Documentation#176]
# Task

We need to port Module 4 of the training manual to QGIS 2.0
### Link to Current

http://manual.linfiniti.com/en/vector_classification/index.html
## Subtasks
- [x] Lesson 1: Text and Screenshots
      Assigned: George
- [x] Lesson 2: Text and Screenshots
      Assigned: George
- [ ] Lesson 3: Text and Screenshots
