### ISSUE TITLE
Module 6: Creating Vector Data - Update English Content

### ISSUE THREAD

**Issue by grvhi** [qgis/QGIS-Documentation#178]
# Task

We need to port Module 6 of the training manual to QGIS 2.0
### Link to Current

http://manual.linfiniti.com/en/vector_classification/index.html
## Subtasks
- [x] Lesson 1: Text and Screenshots
- [x] Lesson 2: Text and Screenshots
- [x] Lesson 3: Text and Screenshots
- [ ] Lesson 4: Text and Screenshots
