### ISSUE TITLE
Module 7: Vector Analysis - Update English Content

### ISSUE THREAD

**Issue by grvhi** [qgis/QGIS-Documentation#179]
# Task

We need to port Module 7 of the training manual to QGIS 2.0
### Link to Current

http://manual.linfiniti.com/en/vector_analysis/index.html
## Subtasks
- [x] Lesson 1: Text 
- [x] Lesson 1: Screenshots - @Erve1879
- [x] Lesson 2: Text
- [x] Lesson 2: Screenshots - @Erve1879
- [x] Lesson 3: Text
- [x] Lesson 3: Screenshots - @Erve1879
- [ ] Lesson 4: Text
- [ ] Lesson 4: Screenshots - @Erve1879
