### ISSUE TITLE
Module 8: Rasters - Update English Content

### ISSUE THREAD

**Issue by grvhi** [qgis/QGIS-Documentation#180]
# Task

We need to port Module 8 of the training manual to QGIS 2.0
### Link to Current

http://manual.linfiniti.com/en/rasters/index.html
## Subtasks
- [x] Lesson 1: Text
- [x] Lesson 1: Screenshots - @Erve1879
- [x] Lesson 2: Text
- [x] Lesson 2: Screenshots - @Erve1879
- [x] Lesson 3: Text
- [x] Lesson 3: Screenshots - @Erve1879
