### ISSUE TITLE
Module 9: Completing the Analysis - Update English Content

### ISSUE THREAD

**Issue by grvhi** [qgis/QGIS-Documentation#181]
# Task

We need to port Module 9 of the training manual to QGIS 2.0
### Link to Current

http://manual.linfiniti.com/en/complete_analysis/index.html
## Subtasks
- [ ] Lesson 1: Text
- [ ] Lesson 1: Screenshots - @Erve1879
- [ ] Lesson 2: Text
- [ ] Lesson 2: Screenshots - @Erve1879
- [ ] Assignment 1: Text
- [ ] Assignment 1: Screenshots - @Erve1879
- [ ] Lesson 3: Text
- [ ] Lesson 3: Screenshots - @Erve1879
