### ISSUE TITLE
Module 14: PostgreSQL - Update English Content

### ISSUE THREAD

**Issue by grvhi** [qgis/QGIS-Documentation#186]
# Task

We need to port Module 6 of the training manual to QGIS 2.0
### Link to Current

http://manual.linfiniti.com/en/postgres/index.html
## Subtasks
- [ ] Lesson 1: Text
- [ ] Lesson 1: Screenshots - @Erve1879
- [ ] Lesson 2: Text
- [ ] Lesson 2: Screenshots - @Erve1879
- [ ] Lesson 3: Text
- [ ] Lesson 3: Screenshots - @Erve1879
- [ ] Lesson 4: Text
- [ ] Lesson 4: Screenshots - @Erve1879
- [ ] Lesson 5: Text
- [ ] Lesson 5: Screenshots - @Erve1879
- [ ] Lesson 6: Text
- [ ] Lesson 6: Screenshots - @Erve1879
