### ISSUE TITLE
Use include to add a Python code section to all processing algorithms

### ISSUE THREAD

**Issue by havatv** [qgis/QGIS-Documentation#5592]
## Description

Goal: Provide a common "Python code" section for all processing algorithm through an include.
Inspired by qgis/QGIS-Enhancement-Proposals#178.
We could also consider adding the algorithm ID in the algorithm documentation.
What to call the "Python code" section is yet to be decided, and the same goes for the contents and structure.

Here is a list of the algorithm sections, with status.  The first checkbox indicates that all is done, the second that something has been done (but not complete).
- [x] [ ] GDAL, Raster analysis (#5621)
- [x] [ ] GDAL, Raster conversion (#5655)
- [x] [ ] GDAL, Raster extraction (#5655)
- [x] [ ] GDAL, Raster miscellaneous (#5655)
- [x] [ ] GDAL, Raster projections (#5655)
- [x] [ ] GDAL, Vector conversion (#5656)
- [x] [ ] GDAL, Vector geoprocessing (#5656)
- [x] [ ] GDAL, Vector miscellaneous (#5656)
- [x] [ ] LAStools (#5659)
- [x] [ ] QGIS, Cartography (#5622)
- [x] [ ] QGIS, Database (#5624)
- [x] [ ] QGIS, File tools (#5626)
- [x] [ ] QGIS, Plots (#5629)
- [x] [ ] QGIS, Interpolation (#5631)
- [x] [ ] QGIS, Layer tools (#5632)
- [x] [ ] QGIS, Modeler tools (#5634)  
- [x] [ ] QGIS, Network analysis (#5637)
- [x] [ ] QGIS, Raster analysis (#5598)
- [x] [ ] QGIS, Raster terrain analysis (#5638)
- [x] [ ] QGIS, Raster tools (#5640)
- [x] [ ] QGIS, Vector analysis (#5643)
- [x] [ ] QGIS, Vector creation (#5644)
- [x] [ ] QGIS, Vector general (#5646)
- [x] [ ] QGIS, Vector geometry (#5581)
- [x] [ ] QGIS, Vector overlay (#5648)
- [x] [ ] QGIS, Vector selection (#5650)
- [x] [ ] QGIS, Vector table (#5652)
- [x] [ ] TauDEM, Basic Grid Analysis (#5796)
- [x] [ ] TauDEM, Specialized Grid Analysis (#5795)
- [x] [ ] TauDEM, Stream Network Analysis (#5799)

**Comment by havatv** [comment]
All algorithms done!
